services:
  postgres:
    container_name: gendocsv3_postgres
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "effective_cache_size=1.5GB"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  bull_redis:
    container_name: gendocsv3_bull_redis
    image: redis:7.4-rc1-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - bull-redis-data:/data

volumes:
  postgres-data:
  bull-redis-data:
