version: '3.0'

services:
  postgres:
    container_name: gendocsv3_postgres
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gendocs-network

  backend:
    container_name: gendocsv3_backend
    image: ${BACKEND_DOCKER_IMAGE}
    restart: always
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - gendocs-network

volumes:
  postgres-data:

networks:
  gendocs-network:
    driver: bridge
