name: Continuous deployment for Gendocs backend

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build artifacts
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          ENV_FILE_CREDENTIALS: ${{ secrets.ENV_FILE_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > ./gcp/credentials.json
          echo "$ENV_FILE_CREDENTIALS" > ./.env

      - name: Build and push tag to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: leninner/gendocsv3:${{ github.ref_name }}

      - name: Build and push latest tag to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: leninner/gendocsv3:latest
